name: Studyflow CI

on:
  push:
    branches:
      - main
      - dev 
  
jobs:
  build:
    name: frontend and backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
    
      - name: build frontend and backend
        run: |
          docker compose build 

  